### ISSUE TITLE
Can you include one example for Reading CSV?

### ISSUE THREAD

**Issue by sujit-baniya** [cnnrznn/gomr#2]
Is it possible for you to include one example for Reading CSV and perform operations on each row to generate more rows in CSV

**Comment by cnnrznn** [comment]
So if I understand correctly, you want to process an input file which is a csv, and produce MR output which is also CSV?

Here is a modified version of the wordcount program, using csv input and output:
https://gist.github.com/cnnrznn/d51e31fd526bf7b124157cf7130dfd8e

To handle CSV input, split the string by comma in the Mapper. If you use `TextFileParallel`, that function feeds data to the Mapper as strings which are the input file split line-by-line.

**Note** `TextFileParallel` will likely change soon to `TextFile`. The naming was just for experimentation but it turns out the other input methods are not as performant.

**Comment by sujit-baniya** [comment]
Thanks! The gist would not handle the data with comma properly
For e.g.
phone,first_name, last_name
+9779856034616,"Mr, ABC", "Roberts"

**Comment by cnnrznn** [comment]
I see. It looks like you allow commas within strings? If so, you have to do some more complicated parsing in the Map function.

If you provide a use case/test/input data I can help develop something

**Comment by sujit-baniya** [comment]
Yes I've a use-case of mapping..

I want to use phone fields from a CSV. use Mapper to verify the phone field to get Country, Carrier
and drop to other CSV along with added columns + columns from previous CSV.

Here I've added a go file that' already doing the job... but I am trying to do it from your library.

[Phone.zip](https://github.com/cnnrznn/gomr/files/4581163/Phone.zip)

phone,first_name,last_name
+35794000000,"Dr. Robert","William"
+35794000001,"Dr. Robert2","William1"
+35794000002,"Dr. Robert3","William3"
+35794000003,"Dr. Robert4","Willia2"

**Comment by sujit-baniya** [comment]
Also it will help me check how efficient your library works for me :)

**Comment by cnnrznn** [comment]
I see. It seems like you only want the "map" part of map-reduce. This library will do that, but there will be extra overhead from the partition and reduce steps. It is possible to pass data through these steps unchanged - see "identity" example, but there will still be overhead.

If you really want to compare the library to what you have:

1. put your `processNumber` logic in the maper
2. You will have to first parse the phone number from the line in the csv, but this should be roughly `strings.Split(number, ",")[0]`
3. Instead of returning a string slice, send the string slice on the outgoing channel

**Comment by sujit-baniya** [comment]
Yeah! I also see some overhead to use Partition and Reduce only for Map...
If we could use them only on-demand and when needed then we could avoid the overhead

**Comment by cnnrznn** [comment]
So places I see in your code that could be optimized:

1. There is only one goroutine putting input on the "src" channel
2. The "src" channel is unbuffered. Although the code is correct, a buffered channel will allow the goroutine generating input to get back to useful work. Otherwise, the sender goroutine will be blocked until the reader goroutine reads the value on the channel.

Your code resembles my `TextFileSerial` function which writes input to a single channel that is read from many goroutine workers. If you look at `TextFileParallel`, that function splits the file into `numberOfMapper` chunks and spins up a goroutine to read lines from within that chunk. There are edge cases, but those are handled by the function. This could be where you speed up.

Here is a gist with my idea: https://gist.github.com/cnnrznn/2fbb0f4b624d79b7e97cb740a43242d0

I am closing this issue because the problem doesn't seem to be with the gomr library. I'm happy to keep chatting, however.

**Comment by cnnrznn** [comment]
Closing, this issue does not represent a problem with GoMR

**Comment by sujit-baniya** [comment]
hi @cnnrznn Your code for mapping works flawlessly much more faster (5x).
How would I use same for Reduce?
For e.g.
counting rows by grouping columns

phone,country,carrier

I would count total rows for combination of country and carrier
